version: '3.8'

services:
  wanderguide:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wanderguide-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - GEOAPIFY_API_KEY=${GEOAPIFY_API_KEY}
      - OPENROUTESERVICE_API_KEY=${OPENROUTESERVICE_API_KEY}
      - NEXT_PUBLIC_SUPABASE_AUTH_URL=${NEXT_PUBLIC_SUPABASE_AUTH_URL}
      - NEXT_PUBLIC_SUPABASE_AUTH_ANON_KEY=${NEXT_PUBLIC_SUPABASE_AUTH_ANON_KEY}
    restart: always
